version: "3.7"

services:

  proxy:
    security_opt:
      - seccomp:"./allow_perf_event_open_seccomp.json"
    cap_drop:
      - ALL
    ulimits:
      memlock:
        soft: -1
        hard: -1
      core:
        soft: -1
        hard: -1
    build:
      context: .
      dockerfile: Dockerfile-proxy
    networks:
      - envoymesh
    ports:
      - "1999:1999"
      - "8001:8001"
    volumes:
      - type: bind
        source: ./proxy_results
        target: /results
    labels:
      org.my-test.role: "proxy"
      org.my-test.filter: "mysql"


  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    networks:
      - envoymesh
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${SYSBENCH_DB_NAME}
    labels:
      org.my-test.role: "database"
      org.my-test.filter: "mysql"

networks:
  envoymesh:
    name: envoymesh
